INSERT INTO tbl_cards (hp, name_stage, info, attack, damage, weak, resis, retreat, collection_id, type_id, stage_id) VALUES
(60, 'Bulbasaur', 'Seed Pokémon', 'Vine Whip', '20', 'Fire', 'None', '1', 1, 1, 1),
(50, 'Charmander', 'Lizard Pokémon', 'Ember', '30', 'Water', 'None', '1', 1, 2, 1),
(50, 'Squirtle', 'Tiny Turtle Pokémon', 'Bubble', '20', 'Lightning', 'None', '1', 1, 3, 1),
(40, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', 'None', '1', 1, 1, 1),
(70, 'Ivysaur', 'Seed Pokémon', 'Razor Leaf', '30', 'Fire', 'None', '2', 1, 1, 2),
(80, 'Charmeleon', 'Flame Pokémon', 'Flamethrower', '50', 'Water', 'None', '2', 1, 2, 2),
(80, 'Wartortle', 'Turtle Pokémon', 'Water Gun', '40', 'Lightning', 'None', '2', 1, 3, 2),
(90, 'Pikachu', 'Mouse Pokémon', 'Thunder Shock', '30', 'Fighting', 'None', '1', 2, 1, 1),
(100, 'Raichu', 'Mouse Pokémon', 'Thunderbolt', '60', 'Fighting', 'None', '2', 2, 1, 2),
(60, 'Jigglypuff', 'Balloon Pokémon', 'Sing', '20', 'Fighting', 'Psychic', '1', 2, 7, 1),
(100, 'Snorlax', 'Sleeping Pokémon', 'Body Slam', '50', 'Fighting', 'None', '3', 2, 7, 1),
(120, 'Gengar', 'Shadow Pokémon', 'Nightmare', '60', 'Psychic', 'Fighting', '2', 3, 5, 2),
(90, 'Machop', 'Superpower Pokémon', 'Karate Chop', '40', 'Psychic', 'None', '1', 3, 6, 1),
(120, 'Machamp', 'Superpower Pokémon', 'Seismic Toss', '60', 'Psychic', 'None', '3', 3, 6, 3),
(70, 'Eevee', 'Evolution Pokémon', 'Quick Attack', '30', 'Fighting', 'None', '1', 2, 7, 1),
(100, 'Vaporeon', 'Bubble Jet Pokémon', 'Water Gun', '50', 'Lightning', 'None', '2', 3, 3, 2),
(100, 'Jolteon', 'Lightning Pokémon', 'Pin Missile', '60', 'Fighting', 'None', '2', 2, 1, 2),
(100, 'Flareon', 'Flame Pokémon', 'Flamethrower', '60', 'Water', 'None', '2', 1, 2, 2),
(90, 'Aerodactyl', 'Fossil Pokémon', 'Wing Attack', '40', 'Lightning', 'Fighting', '2', 3, 7, 1),
(110, 'Dragonite', 'Dragon Pokémon', 'Hyper Beam', '70', 'Colorless', 'None', '3', 2, 7, 3);
