INSERT INTO tbl_cards (hp, name_stage, info, attack, damage, weak, resis, retreat, collection_id, type_id, stage_id) VALUES
(70, 'Oddish', 'Weed Pokémon', 'Absorb', '20', 'Fire', 'None', '1', 2, 1, 1),
(90, 'Gloom', 'Weed Pokémon', 'Poison Powder', '30', 'Fire', 'None', '2', 1, 2, 2),
(110, 'Vileplume', 'Flower Pokémon', 'Solar Beam', '60', 'Fire', 'None', '2', 1, 2, 3),
(60, 'Meowth', 'Scratch Cat Pokémon', 'Pay Day', '20', 'Fighting', 'None', '1', 2, 7, 1),
(90, 'Persian', 'Classy Cat Pokémon', 'Slash', '40', 'Fighting', 'None', '2', 2, 7, 2),
(80, 'Psyduck', 'Duck Pokémon', 'Confusion', '20', 'Lightning', 'None', '1', 3, 3, 1),
(100, 'Golduck', 'Duck Pokémon', 'Hydro Pump', '50', 'Lightning', 'None', '2', 3, 3, 2),
(60, 'Abra', 'Psi Pokémon', 'Teleport', 'None', 'Psychic', 'None', '1', 3, 5, 1),
(90, 'Kadabra', 'Psi Pokémon', 'Confusion', '30', 'Psychic', 'None', '2', 3, 5, 2),
(110, 'Alakazam', 'Psi Pokémon', 'Psychic', '60', 'Psychic', 'None', '3', 3, 5, 3),
(70, 'Geodude', 'Rock Pokémon', 'Tackle', '20', 'Grass', 'None', '1', 3, 6, 1),
(90, 'Graveler', 'Rock Pokémon', 'Rock Throw', '40', 'Grass', 'None', '2', 3, 6, 2),
(120, 'Golem', 'Megaton Pokémon', 'Explosion', '80', 'Grass', 'None', '3', 3, 6, 3),
(60, 'Gastly', 'Gas Pokémon', 'Lick', '10', 'Psychic', 'None', '1', 3, 5, 1),
(80, 'Haunter', 'Gas Pokémon', 'Nightmare', '30', 'Psychic', 'None', '2', 3, 5, 2),
(120, 'Onix', 'Rock Snake Pokémon', 'Rock Throw', '40', 'Grass', 'None', '3', 3, 6, 1),
(100, 'Hitmonlee', 'Kicking Pokémon', 'Stretch Kick', '50', 'Psychic', 'None', '2', 3, 6, 1),
(100, 'Hitmonchan', 'Punching Pokémon', 'Special Punch', '50', 'Psychic', 'None', '2', 3, 6, 1),
(90, 'Scyther', 'Mantis Pokémon', 'Slash', '30', 'Fire', 'None', '1', 2, 1, 1),
(110, 'Pinsir', 'Stag Beetle Pokémon', 'Guillotine', '60', 'Fire', 'None', '2', 1, 1, 1),
(60, 'Magikarp', 'Fish Pokémon', 'Splash', 'None', 'Lightning', 'None', '1', 3, 3, 1),
(90, 'Gyarados', 'Atrocious Pokémon', 'Dragon Rage', '50', 'Lightning', 'None', '2', 3, 3, 2),
(120, 'Lapras', 'Transport Pokémon', 'Water Gun', '40', 'Lightning', 'None', '3', 3, 3, 1),
(70, 'Cubone', 'Lonely Pokémon', 'Bone Club', '20', 'Grass', 'None', '1', 3, 6, 1),
(90, 'Marowak', 'Bone Keeper Pokémon', 'Bonemerang', '40', 'Grass', 'None', '2', 3, 6, 2),
(100, 'Kangaskhan', 'Parent Pokémon', 'Comet Punch', '40', 'Fighting', 'None', '2', 2, 7, 1),
(110, 'Tauros', 'Wild Bull Pokémon', 'Rampage', '50', 'Fighting', 'None', '2', 2, 7, 1),
(120, 'Zapdos', 'Electric Pokémon', 'Thunder', '70', 'Fighting', 'None', '3', 2, 2, 3),
(120, 'Moltres', 'Flame Pokémon', 'Fire Blast', '70', 'Water', 'None', '3', 1, 2, 3),
(120, 'Articuno', 'Freeze Pokémon', 'Blizzard', '70', 'Lightning', 'None', '3', 3, 3, 3);
