INSERT INTO tbl_cards (hp, name_stage, info, attack, damage, weak, resis, retreat, collection_id, type_id, stage_id) VALUES
(70, 'Sandshrew', 'Mouse Pokémon', 'Scratch', '20', 'Water', 'None', '1', 1, 6, 1),
(90, 'Sandslash', 'Mouse Pokémon', 'Slash', '40', 'Water', 'None', '2', 1, 6, 2),
(60, 'Diglett', 'Mole Pokémon', 'Dig', '20', 'Grass', 'None', '1', 3, 6, 1),
(80, 'Dugtrio', 'Mole Pokémon', 'Earthquake', '50', 'Grass', 'None', '2', 3, 6, 2),
(70, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '20', 'Fighting', 'None', '1', 2, 2, 1),
(90, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '60', 'Fighting', 'None', '2', 2, 2, 2),
(60, 'Voltorb', 'Ball Pokémon', 'Tackle', '20', 'Fighting', 'None', '1', 2, 2, 1),
(80, 'Electrode', 'Ball Pokémon', 'Explosion', '70', 'Fighting', 'None', '2', 2, 2, 2),
(70, 'Koffing', 'Poison Gas Pokémon', 'Smog', '20', 'Psychic', 'None', '1', 3, 5, 1),
(90, 'Weezing', 'Poison Gas Pokémon', 'Sludge', '40', 'Psychic', 'None', '2', 3, 5, 2),
(60, 'Rhyhorn', 'Spikes Pokémon', 'Horn Attack', '30', 'Grass', 'None', '2', 3, 6, 1),
(100, 'Rhydon', 'Drill Pokémon', 'Horn Drill', '60', 'Grass', 'None', '3', 3, 6, 2),
(70, 'Horsea', 'Dragon Pokémon', 'Smokescreen', '20', 'Lightning', 'None', '1', 3, 3, 1),
(90, 'Seadra', 'Dragon Pokémon', 'Water Gun', '40', 'Lightning', 'None', '2', 3, 3, 2),
(120, 'Seaking', 'Goldfish Pokémon', 'Horn Attack', '50', 'Lightning', 'None', '2', 3, 3, 2),
(60, 'Staryu', 'Star Shape Pokémon', 'Slap', '20', 'Lightning', 'None', '1', 3, 3, 1),
(90, 'Starmie', 'Mysterious Pokémon', 'Recover', '40', 'Lightning', 'None', '2', 3, 3, 2),
(70, 'Shellder', 'Bivalve Pokémon', 'Clamp', '20', 'Lightning', 'None', '1', 3, 3, 1),
(100, 'Cloyster', 'Bivalve Pokémon', 'Spike Cannon', '50', 'Lightning', 'None', '2', 3, 3, 2),
(60, 'Krabby', 'River Crab Pokémon', 'Vice Grip', '20', 'Lightning', 'None', '1', 3, 3, 1),
(90, 'Kingler', 'Pincer Pokémon', 'Crabhammer', '50', 'Lightning', 'None', '2', 3, 3, 2),
(70, 'Exeggcute', 'Egg Pokémon', 'Hypnosis', '20', 'Fire', 'None', '1', 1, 1, 1),
(100, 'Exeggutor', 'Coconut Pokémon', 'Stomp', '50', 'Fire', 'None', '2', 1, 1, 2),
(60, 'Cubone', 'Lonely Pokémon', 'Headbutt', '20', 'Grass', 'None', '1', 3, 6, 1),
(90, 'Marowak', 'Bone Keeper Pokémon', 'Bone Club', '40', 'Grass', 'None', '2', 3, 6, 2),
(120, 'Chansey', 'Egg Pokémon', 'Double-Edge', '80', 'Fighting', 'None', '2', 2, 7, 1),
(100, 'Mr. Mime', 'Barrier Pokémon', 'Meditate', '40', 'Psychic', 'None', '2', 3, 5, 1),
(120, 'Ditto', 'Transform Pokémon', 'Transform', 'None', 'Fighting', 'None', '1', 2, 7, 1),
(130, 'Mewtwo', 'Genetic Pokémon', 'Psychic', '70', 'Psychic', 'None', '3', 3, 5, 3),
(100, 'Mew', 'New Species Pokémon', 'Pound', '40', 'Psychic', 'None', '3', 3, 5, 1);
